version: '3.7'
services:
  dev:
    container_name: flask_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    tty: True
    # environment:
    #   FLASK_APP: flaskr
    #   FLASK_ENV: development
    ports:
      - 5001:5001
    #entrypoint: flask run --host 0.0.0.0 --port 5001
    entrypoint: python hello.py